# Generated by Django 2.2 on 2019-05-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('badgeNumber', models.IntegerField()),
                ('dateJoined', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
